### ISSUE TITLE
nptextcite with multiple sources needs a semicolon

### ISSUE THREAD

**Issue by jjhaegele** [plk/biblatex-apa#78] opened 2019-06-05 07:20 UTC
As far as I understand `\nptextcites` its only use is within parentheses as a substitute for `\parencite`.

So, I wondered why multiple citations are seperated by a comma with `\nptextcites` instead of a semicolon 

A semicolon is used with `\parencite` and would be according to the apa manual, see https://www.apastyle.org/learn/faqs/references-in-parentheses. 

Take the last example from the apa website: _(Minor, 2001; see also Adams, 1999; Storandt, 2007)_. I would like to create this with `(\nptextcite{minor2001}; see also \nptextcites{adams1999,storandt2007})` (or the like), but would get _(Minor, 2001; see also Adams, 1999, Storandt, 2007)_ by now.

Any problems with changing the behaviour of `\nptextcites` to deviate from `\textcite` in this manner?

In any case, thanks for the great package!

_Edit: Used `\nptextcites` for multiple citations. Behavior remains the same.

**Comment by moewew** [comment] 2019-06-05 14:58
`\nptextcites` is also a bit inconsistent in that regard. Like `\textcite` `\nptextcite` builds directly upon `\usebibmacro{textcite}` (it just sets a flag to drop parentheses), so `\nptextcite` produces commas (`\compcitedelim`), yet the multicite command is defined with `\multicitedelim`

https://github.com/plk/biblatex-apa/blob/ad7c5d025293fa2ae51cf1f7ae4037129a49d903/tex/latex/biblatex-apa/cbx/apa.cbx#L373

This leads to the apparent inconsistency shown in the MWE below.

@jjhaegele For the shown use case you don't need `\nptextcites` at all. `\parencites` is all you need. But of course the general point still stands.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\parencites{sigfridsson}[see also][]{worman,geer}

\nptextcites{sigfridsson}{worman,geer}

\printbibliography
\end{document}
```

**Comment by moewew** [comment] 2019-09-08 08:03
@plk  What do you think about this? Fundamentally, should `\nptextcites` be based on `\textcite` or on `\parencite`?

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\nptextcite{sigfridsson}

\textcite{sigfridsson}

\parencite{sigfridsson}

\nptextcite{sigfridsson,nussbaum}

\textcite{sigfridsson,nussbaum}

\parencite{sigfridsson,nussbaum}

\printbibliography
\end{document}
```
See also the superfluous space in the `\nptextcite` that is probably caused by https://github.com/plk/biblatex-apa/issues/73 (I think the code suggested there should fix this).

**Comment by plk** [comment] 2019-09-08 09:46
I'm open to suggestions - that macro was put in a long, long time ago and is clumsy, probably not having much justification at all any more. I was planning to revisit all of this when the APA publish the 7th edition this year when I'll have to update the whole package anyway.

**Comment by moewew** [comment] 2019-09-08 16:16
I might be misunderstanding what `\nptextcite` was supposed to do, but I always saw it as a kind of `\parencite` but without the parentheses. Then building upon `\parencite` would seem more natural.

**Comment by plk** [comment] 2019-11-23 22:08
Will be fixed in v9.1

**Comment by moewew** [comment] 2019-11-29 17:00
The spurious space from #73 is indeed fixed, but with version 9.1 the following MWE produces
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}


\begin{document}
\parencite{sigfridsson,worman,geer}

(\nptextcite{sigfridsson,worman,geer})

(\nptextcites{sigfridsson}[see also][380]{worman}[12]{geer})

\end{document}
```
> (Geer, 1985; Sigfridsson & Ryde, 1998; Worman, 2002)
>
> (Geer, 1985, Sigfridsson & Ryde, 1998, Worman, 2002)
>
> (Sigfridsson & Ryde, 1998; see also, Worman, 2002, p. 380, Geer, 1985, p. 12)

that is to say `\nptextcite` uses commas as `\multicitedelim` and `\parencite` uses semicolons. But `\nptextcite` sometimes uses semicolons when there is a prenote for multiple citations.

I don't know what the APA manual has to say about that but at least the inconsistency in the last line look odd. (Though I could believe that the APA manual wants exactly that.)

**Comment by plk** [comment] 2019-11-29 21:04
That looks wrong - as far as I know, there are no APA examples for such situations but it should like like textcites and so no semi-colons.

**Comment by moewew** [comment] 2020-04-05 08:09
As a data point: `apacite` has a command `\citeNP`, which looks like it could be equivalent to `biblatex-apa`'s `\nptextcite`. `\citeNP` is described as

>  `\cite` without the parentheses.  This is useful for complex constructions like
> ```latex
>\citeauthor{Jone01} (\citeyearNP{Jone01}; see also \citeNP{SmJo03})
> ```

And `apacite`'s `\cite` is practically `biblatex-apa`'s `\parencite`, so in `apacite` `\nptextcite` is based on `\parencite`, not on `\textcite`.

**Closed** 2020-04-27 20:24 UTC
