### ISSUE TITLE
On the ambiguous compression of multiple authors

### ISSUE THREAD

**Issue by rmolina** [plk/biblatex-apa#150] opened 2021-10-20 21:23 UTC
Please consider the following MWE:

```latex
\documentclass{article}
\usepackage[style=apa]{biblatex}
\addbibresource{\jobname.bib}

\begin{filecontents}[force]{\jobname.bib}
@BOOK{One,
	AUTHOR = {Author Red and Author Green and Author Blue},
	TITLE = {Title One},
	DATE = {2019},
	PUBLISHER = {Publisher},
}
@BOOK{Two,
	AUTHOR = {Author Red and Author Yellow and Author Green and Author Blue},
	TITLE = {Title Two},
	DATE = {2020},
	PUBLISHER = {Publisher},
}
@BOOK{Three,
	AUTHOR = {Author Red and Author Green and Author Blue and Author Black},
	TITLE = {Title Three},
	DATE = {2021},
	PUBLISHER = {Publisher},
}
\end{filecontents}

\begin{document}
\parencite{One,Two,Three}
\printbibliography
\end{document}
```

This code results in the citation `(Red et al., 2019; Red et al., 2021; Red et al., 2020)`. I believe this should be `(Red et al., 2019, 2020, 2021)`.

I could not find anything specific about this case (ambiguous compression of multiple authors) in the Publication Manual. Still, at the end of Section 8.12, it says: _In the case of multiple works in which some author names have been abbreviated to “et al.” (see Section 8.17), place the citations in chronological order (regardless of the order in which they appear in the reference list)._

I think this clarification note is precisely about this case. If this were about multiple works from the same authors, we would use chronological order anyway because they get chronologically sorted in the reference list. In such a case, we would not need this clarification.

What do you think?

EDIT: removed duplicated AUTHOR fields.

**Comment by PsychicBirdy** [comment] 2022-02-17 12:46
I'm pretty sure rmolina is right. (There is no need for the duplicate other field, so I'm referring to moewew's MWE.) To reiterate, APA manual p. 263 says "In the case of multiple works in which some author names have been abbreviated to 'et al.' (see Section 8.17), place the citations in chronological order (regardless of the order in which they appear in the reference list)." 

I don't think this implies "In the case of multiple works [by the same list of authors]" as plk suggests. In the case of multiple works by the same list of authors there wouldn't be the need for this clarification note. In-text citation order and reference list order simply cannot differ in such a case because if all the authors are identical, the next criterion for ordering is the date, and so in-text order and reference list order would be sorted by date and thus would be identical.

The only time the order in which references appear in the reference list may differ from the order in text is when subsequent authors differ. In the reference list, they are printed in full and sorted in alphabetical order of the authors. In text, the authors may be abbreviated to "first author et al." and thus potentially can be sorted in a different way.

The argument that "(Red et al., 2019, 2020, 2021) is misleading, implying that the same list of authors wrote 3 papers in different years" would only make sense if the APA manual would suggest such an ordering in order to enable one to differentiate between ambiguous cases. However, such an ordering is not suited for an unambiguous differentiation. Consider slightly different references:
Red, A., Green, A., & Blue, A. (2019). Title one. Publisher.
Red, A., Green, A., Blue, A., & Black, A. (2020). Title three. Publisher.
Red, A., Yellow, A., Green, A., & Blue, A. (2021). Title two. Publisher.
This would result in the in-text citation (Red et al., 2019, 2020, 2021) even though the authors are not identical. (Red et al., 2019, 2020, 2021) does not imply that the same list of authors wrote 3 papers in different years. We simply cannot tell whether these references are written by identical authors or not when only looking at the in-text citation. We need to look at the references in the reference list for that. All the in-text citation needs to do is enable one to clearly identify to which reference in the reference list an in-text citation is referring to. This is what section 8.18 is about.

So TL,DR: rmolina is right,
Red, A., Green, A., & Blue, A. (2019). Title one. Publisher.
Red, A., Green, A., Blue, A., & Black, A. (2021). Title three. Publisher.
Red, A., Yellow, A., Green, A., & Blue, A. (2020). Title two. Publisher.
should be sorted (Red et al., 2019, 2020, 2021), not (Red et al., 2019; Red et al., 2021; Red et al., 2020).

**Comment by plk** [comment] 2022-02-17 14:09
I'm not sure either of these solutions are correct. The `uniquelist` expansion mandated in 8.18 should result in:

```
(Red, A. Green, A. & Blue, A. 2019; Red, A. Yellow, A. et al 2020; Red, A. Green, A., Blue, A. & Black, A. 2021)
```

It is mandated to expand the lists to the point of non-ambiguity with other lists. This necessity is in fact why I implemented the `uniquelist` feature in the first place. If we can agree on the correct solution, I will have a look at what is going on.

**Comment by plk** [comment] 2022-02-17 14:45
Sorry, yes, there is no need for the initials, just copy-pasting without thinking. The key in 8.18 seems to be to be the phrase "shorten to the same form". It is true that the examples are all in the year.

**Comment by plk** [comment] 2022-02-17 15:02
I'm contacting the APA about this to get clarification. They are usually helpful when asked as I've had to do this before for similar questions.

**Comment by PsychicBirdy** [comment] 2022-02-17 15:26
I agree, "shorten to the same form" is the key.
Alright, let's see what they will tell us.

**Comment by plk** [comment] 2022-02-17 17:58
They have replied and you are correct, with different years, it's:

```
(Red et al., 2019, 2020, 2021)
```

with identical years the list disambiguation applies:

```
(Red, Green, & Blue, 2021; Red, Green, Blue, & Black, 2021; Red, Yellow, et al., 2021)
```

so I will look into this.

**Comment by plk** [comment] 2022-02-17 19:58
This will be fixed in the next release. It's interesting that the fix was a reversion of a legacy fix for a different issue that was resolved another way some time ago and the legacy fix was now in fact the cause of this issue.

**Comment by PsychicBirdy** [comment] 2022-02-17 20:30
Oh, they replied so fast.
You are right, it's even already in the style examples PDF. So basically, this was already implemented but you disimproved it along the way, right? I cannot even imagine how much code the APA style needs. The style is so complex.
Anyway, thanks for fixing it. I'm looking forward to testing it once it's out. Keep up the good work!

**Comment by plk** [comment] 2022-02-17 20:41
It was already implemented but I hadn't tested multicites in that scenario and had an old fix for something that was no longer an issue which made it not work. It is a beast of a style and made me take on `biber` in the first place as the auto-expansion of name lists was a requirement and `biblatex` couldn't do that with `bibtex` ...

**Closed** 2022-06-22 13:17 UTC
