### ISSUE TITLE
Missing the possibility to cite the dates of works that are published seasonally

### ISSUE THREAD

**Issue by PsychicBirdy** [plk/biblatex-apa#155] opened 2022-02-04 11:38 UTC
... at least I haven't found a notation that would do this. There is an explicit example on how to cite the date of works that are published seasonally in APA 7 manual on page 290: "(2020, Spring/Summer)." I also stumbled upon several magazines that are published seasonally, so this has indeed some use.

I don't know how to program this, but here is an idea how the notation could look like. There is an ISO standard that has this partially covered, see here: https://tex.stackexchange.com/questions/396421/best-way-to-encode-season-spring-summer-fall-winter-in-bibtex
According to this standard
(2022, Spring) is noted as 2022-21
(2022, Summer) as 2022-22
(2022, Fall) as 2022-23
(2022, Winter) as 2022-24

However, I would suggest the following notation to also cover bi-seasonally published works:
(2022, Spring) as 2022-21
Spring/Summer as 22
Summer as 23
Summer/Fall as 24
Fall as 25
Fall/Winter as 26
Winter as 27
Winter/Spring as 28

Maybe even the possibility to use a custom expression for odd dates like (2022, Spring/Summer/Fall) would be useful. This would be difficult to sort though.

I also asked on stackexchange about this issue: https://tex.stackexchange.com/questions/632264/how-to-cite-a-magazine-published-seasonally-in-apa-style-with-biblatex

(Edit: I changed "Autumn" to "Fall" since it is an American style.)

**Comment by plk** [comment] 2022-02-16 13:48
This is already implemented, see the `biblatex` manual page 41 (Table 5). The season strings appear in the data field `yeardivision` and are localised.

**Comment by PsychicBirdy** [comment] 2022-02-16 16:06
Thanks a lot for your reply. Two questions:
1. How do I make yeardivision show up? With the following MWE

```
\documentclass{scrbook}
\usepackage[utf8]{inputenc}
\usepackage[american]{babel}
\usepackage[backend=biber,style=apa,sorting=none,sortlocale=auto,autolang=hyphen]{biblatex}
\begin{filecontents}{\jobname.bib}
@ARTICLE{10.1:15a,
  ENTRYSUBTYPE   = {nonacademic},
  AUTHOR         = {E. M. Puckett},
  TITLE          = {Printing protection for {S}outhwest {V}irginia healthcare professionals},
  JOURNALTITLE   = {Imagine: University Libraries at Virginia Tech Magazine},
  VOLUME         = {1},
  NUMBER         = {2},
  PAGES          = {4--5},
  DATE           = {2004-22}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

\textcite{10.1:15a}

\printbibliography
\end{document}
```

I get

> Puckett, E. M. (2004). Printing protection for Southwest Virginia healthcare profession-
als. Imagine: University Libraries at Virginia Tech Magazine, 1(2), 4–5.

This is in line with the biblatex manual, p. 41, saying 2004-22 has the output format "2004". However, according to the APA manual it should look like this:

> Puckett, E. M. (2004, Summer). Printing protection for Southwest Virginia healthcare profession-
als. Imagine: University Libraries at Virginia Tech Magazine, 1(2), 4–5.

2. On p. 297 of the biblatex manual only yeardivisions like Summer, Winter, etc. are listed. That's in line with iso8601-2 Extended Format dates, I guess. However, APA (p. 290) explicitly demands that also something like "Spring/Summer" shall be possible. This is not implemented yet, is it?

**Comment by plk** [comment] 2022-02-16 20:36
This will be in the next release which should be out in the next few days.

**Comment by PsychicBirdy** [comment] 2022-02-17 11:11
Thanks a lot! I will test it when it's out.

**Comment by moewew** [comment] 2022-02-18 07:10
There seems to be a slight discrepancy between citation and bibliography here

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[american]{babel}
\usepackage[backend=biber,style=apa]{biblatex}

\begin{filecontents}{\jobname.bib}
@ARTICLE{10.1:15a,
  ENTRYSUBTYPE   = {nonacademic},
  AUTHOR         = {E. M. Puckett},
  TITLE          = {Printing Protection for {Southwest Virginia} Healthcare Professionals},
  JOURNALTITLE   = {Imagine: University Libraries at Virginia Tech Magazine},
  VOLUME         = {1},
  NUMBER         = {2},
  PAGES          = {4--5},
  DATE           = {2004-21/2004-22}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\textcite{10.1:15a}

\printbibliography
\end{document}
```

> Puckett (2004, Spring)
>
> Puckett, E. M. (2004, Spring/Summer). Printing protection for Southwest Virginia healthcare professionals. Imagine: University Libraries at Virginia Tech Magazine, 1(2), 4–5.

![Screenshot of the output reproduced above](https://user-images.githubusercontent.com/6755835/154634689-83b0029d-2745-4a72-b842-ca90e9b57281.png)

I'm not sure if the yeardivision should appear in citations, but if it should, it should probably be "Spring/Summer", not just "Spring".

**Comment by plk** [comment] 2022-02-18 13:04
Should be fixed in the last commit - that has been a long-standing issue I think, just not caught before.

**Closed** 2022-06-22 13:16 UTC
