### ISSUE TITLE
phdthesis not rendering correctly

### ISSUE THREAD

**Issue by wjakethompson** [plk/biblatex-apa#112] opened 2020-05-18 16:33 UTC
I render PDFs through R Markdown, so apologies in advance if I'm missing some subtleties that would solve this problem more directly. I'm trying to reference a dissertation, but am unable to replicate the reference style in APA7. In the example below from the APA manual, the normal fields do not populate the reference correctly (i.e., "Doctoral dissertation" in with publication number instead of school; school not in brackets). I'm able to work around this by changing the type to `Publication` and moving the school to the `titleaddon` field in the bibtex file.

I originally asked the question on [Tex stackexchange](https://tex.stackexchange.com/questions/544935/formatting-biblatex-phdthesis-for-apa7), and it was suggested that this may be a bug that should be reported here.

bibtex file (`phd.bib`):
```
@phdthesis{example,
  author = {Hollander, M. M.},
  year = {2017},
  title = {Resistance to authority: Methodological innovations and new lessons from the {Milgram} experiment},
  number = {10289373},
  school = {University of Wisconsin-Madison},
  publisher = {{ProQuest Dissertations and Theses Global}}
}

@phdthesis{example2,
  author = {Hollander, M. M.},
  year = {2017},
  title = {Resistance to authority: Methodological innovations and new lessons from the {Milgram} experiment},
  type = {Publication},
  number = {10289373},
  titleaddon = {{Doctoral dissertation, University of Wisconsin-Madison}},
  publisher = {{ProQuest Dissertations and Theses Global}}
}

```

R Markdown:

```
---
output:
  bookdown::pdf_document2:
    keep_tex: true
    latex_engine: "xelatex"
    citation_package: "biblatex"
bibliography: ["bib/phd.bib"]
biblio-style: apa
biblatexoptions:
  - sortcites
csl: csl/apa.csl
toc: false
---

Here is the first example: @example.

Here is the second example: @example2.

# References
```

Output:
<img width="855" alt="Screen Shot 2020-05-18 at 11 28 37 AM" src="https://user-images.githubusercontent.com/6980750/82237090-bbe7d480-98fa-11ea-921e-6f73eebc211b.png">

**Comment by moewew** [comment] 2020-05-18 20:40
`biblatex-apa-test-references.bib` actually contains an entry that does pretty much what your `example2` does

https://github.com/plk/biblatex-apa/blob/a0f1c3cd77f38bb9e06865fe8620f9fca6c7e49d/bibtex/bib/biblatex-apa-test-references.bib#L1560-L1593

But I think that `biblatex-apa` should ideally support the same input as the standard styles for theses.

I have something that almost works. The only thing I'm struggling with is what to do with the "Publication No." obviously the number itself should go into `number`. Currently the "Publication" bit goes into `type`, but classically that is where "Doctoral Dissertation" etc. lives, so that won't work. (Intuitively I wanted to take `series`, because `series`+`number` often go together, but that just isn't right.)

**Comment by ntrocado** [comment] 2022-01-26 00:44
I think that the test examples are not ideal... Using `titleaddon` doesn't allow for localization-agnostic bib files. 

According to the biblatex docs, the `type` field should be used with one of the following keys: `bathesis`, `mathesis`, `phdthesis`, `candthesis`. The exact string would be defined somewhere else, according to language settings. The `institution` field should also be used, and not moved into `titleaddon`, further overloading it, like in examples 10.6:65 and 10.6:66.

`number` and `series` are not available fields under `thesis`. Maybe information like publication numbers should go into `titleaddon` or `note`?

**Comment by plk** [comment] 2022-02-17 21:04
I suspect we can close this as the APA 7th edition version of the style is now release?

**Comment by plk** [comment] 2022-02-19 16:44
@moewew - a bit belated but you mention above that you has some idea about this? I agree that a more standard use of fields would be preferable here which would presumably mean a few more localisation strings in the APA style.

**Comment by moewew** [comment] 2022-02-20 08:22
Mhh, I don't remember everything. Here is how far I got when I looked at this https://github.com/plk/biblatex-apa/compare/master...moewew:rebthes.

**Comment by plk** [comment] 2022-02-20 22:29
Should be better now. `thesis` entries are using the standard `phdthesis` and 'mastersthesis` auto-mapped variants and the use of `TITLEADDON` is removed with `TYPE`, `NUMBER` being used instead.

**Comment by ntrocado** [comment] 2022-02-26 17:18
Much better, thank you!
The only thing is that I'm getting "(Doctoral dissertation)", between parenthesis, when I think it should use square brackets (see section 10.6 of the APA7 manual).

**Comment by plk** [comment] 2022-02-27 13:33
Can you give an example of this? It should be be square brackets, as you say and the reference regression docs do have the square brackets.

**Closed** 2022-06-22 13:20 UTC
