### ISSUE TITLE
year field is not used with newest biblatex/biber as labeldatesource.

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex-apa#28] opened 2016-09-16 07:49 UTC
See https://tex.stackexchange.com/q/329859/2388.

I can reproduce the problem in miktex which has already biblatex 3.5 / biber 2.6.

**Comment by plk** [comment] 2016-09-16 07:53
There is a 3.6 update coming out today along with a 7.1 APA style.

**Comment by u-fischer** [comment] 2016-09-16 07:54
Will it also correct this bug: http://tex.stackexchange.com/questions/329866/getting-undefined-control-sequence-error?

**Comment by jspitz** [comment] 2016-09-16 08:59
This is a duplicate of #27.

**Comment by moewew** [comment] 2016-09-16 14:35
@u-fischer That problem should be fixed with version 7.0 already, see https://github.com/plk/biblatex-apa/issues/26 and http://tex.stackexchange.com/q/329411/.

**Comment by jspitz** [comment] 2016-09-16 15:33
No #26 was actually fixed after the release of 7.0.

**Comment by jspitz** [comment] 2016-09-16 15:35
Sorry, I was referring to the original problem (and #27). @moewew is of course right as far as the second problem is concerned.

**Comment by plk** [comment] 2016-09-17 21:11
`biblatex` 3.6 and `biblatex-apa` 7.1 are now on CTAN.

**Closed by plk** 2016-09-17 21:11 UTC
